modLoader="javafml"
loaderVersion="[37,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="wildplants"
version="1.17.1_2.1.5_forge"
displayName="Wildplants"
credits="WOLFKIDSOUNDS"
displayURL="https://wolfkidsounds.com"
authors="WOLFKIDsounds"
description='''
Adds wild plant generation mainly used for crops that should generate in the wild.
'''

[[dependencies.wildplants]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1]"
ordering="NONE"
side="BOTH"