modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="wildplants"
version="1.16.5_2.1.0"
displayName="Wildplants"
credits="WOLFKIDSOUNDS"
displayURL="https://wolfkidsounds.com"
authors="WOLFKIDsounds"
description='''
Adds wild plant generation mainly used for crops that should generate in the wild.
'''

[[dependencies.wildplants]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"