modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="wildplants"
version="1.16.5_2.5.1_forge"
displayName="Wildplants"
credits="WOLFKIDSOUNDS"
displayURL="https://wolfkidsounds.com"
authors="WOLFKIDsounds"
description='''
This mod adds wild plants (crops) similar to the farmers delight or croptopia world generation.
'''

[[dependencies.wildplants]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"