@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package wks.wolfkidsounds.wildplants.block;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;